SELECT
    p.PRODUCT_CODE,
    SUM(o.SALES_AMOUNT * p.PRICE) AS SALES
FROM
    OFFLINE_SALE o
INNER JOIN PRODUCT p ON o.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    p.PRODUCT_CODE
ORDER BY
    SALES DESC,
    p.PRODUCT_CODE ASC;
